name: ci_tools
version: 0.0.1
author: Louis Orleans <louis@orleans.io>
homepage: https://github.com/dudeofawesome/hn_flutter
publish_to: none

environment:
  sdk: '>=2.0.0-dev.16.0 <3.0.0'
dev_dependencies:
  ansicolor: ^0.1.0
  args: ^1.4.1
  pub_semver: ^1.3.7
  yaml: ^2.1.13
